# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

jobs:
# Builds
- job: macOS
  pool:
    vmImage: 'macOS-11'
  steps:
  - task: Xcode@5
    inputs:
      actions: 'build'
      scheme: 'SlackKit'
      sdk: 'macosx'
      configuration: 'Release'
      xcWorkspacePath: 'SlackKit.xcodeproj/project.xcworkspace'
      xcodeVersion: specifyPath
      xcodeDeveloperDir: '/Applications/Xcode_13.0.app/Contents/Developer'
  - task: Xcode@5
    inputs:
      actions: 'test'
      scheme: 'SlackKitTests'
      sdk: 'macosx'
      configuration: 'Debug'
      xcWorkspacePath: 'SlackKit.xcodeproj/project.xcworkspace'
      xcodeVersion: specifyPath
      xcodeDeveloperDir: '/Applications/Xcode_13.0.app/Contents/Developer'
- job: iOS
  pool:
    vmImage: 'macOS-11'
  steps:
  - task: Xcode@5
    inputs:
      actions: 'build'
      scheme: 'SlackKit'
      sdk: 'iphoneos'
      configuration: 'Release'
      xcWorkspacePath: 'SlackKit.xcodeproj/project.xcworkspace'
      xcodeVersion: specifyPath
      xcodeDeveloperDir: '/Applications/Xcode_13.0.app/Contents/Developer'
  - task: Xcode@5
    inputs:
      actions: 'test'
      scheme: 'SlackKitTests'
      sdk: 'iphonesimulator'
      configuration: 'Debug'
      xcWorkspacePath: 'SlackKit.xcodeproj/project.xcworkspace'
      xcodeVersion: specifyPath
      xcodeDeveloperDir: '/Applications/Xcode_13.0.app/Contents/Developer'
      destinationPlatformOption: 'custom'
      destinationPlatform: 'iOS'
      destinationTypeOption: 'simulators'
      destinationSimulators: 'iPhone 13 Pro,OS=15.0'

- job: tvOS
  pool:
    vmImage: 'macOS-11'
  steps:
  - task: Xcode@5
    inputs:
      actions: 'build'
      scheme: 'SlackKit'
      sdk: 'appletvos'
      configuration: 'Release'
      xcWorkspacePath: 'SlackKit.xcodeproj/project.xcworkspace'
      xcodeVersion: specifyPath
      xcodeDeveloperDir: '/Applications/Xcode_13.0.app/Contents/Developer'
  - task: Xcode@5
    inputs:
      actions: 'test'
      scheme: 'SlackKitTests'
      sdk: 'appletvsimulator'
      configuration: 'Debug'
      xcWorkspacePath: 'SlackKit.xcodeproj/project.xcworkspace'
      xcodeVersion: specifyPath
      xcodeDeveloperDir: '/Applications/Xcode_13.0.app/Contents/Developer'
      destinationPlatformOption: 'custom'
      destinationPlatform: 'tvOS'
      destinationTypeOption: 'simulators'
      destinationSimulators: 'Apple TV 4K,OS=15.0'
- job: Linux
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - script: |
      # Install Swift dependencies
      sudo apt-get install clang libicu-dev
      # Install Swift 5.5.2
      curl https://download.swift.org/swift-5.5.2-release/ubuntu1804/swift-5.5.2-RELEASE/swift-5.5.2-RELEASE-ubuntu18.04.tar.gz > $(Build.SourcesDirectory)/swift-5.5.2-RELEASE-ubuntu18.04.tar.gz
      tar xzf swift-5.5.2-RELEASE-ubuntu18.04.tar.gz -C $(Build.SourcesDirectory)
      # Swift build
      $(Build.SourcesDirectory)/swift-5.5.2-RELEASE-ubuntu18.04/usr/bin/swift build
      # Swift test
      $(Build.SourcesDirectory)/swift-5.5.2-RELEASE-ubuntu18.04/usr/bin/swift test
# Examples
- job: 'Swift_Package_Manager'
  pool:
    vmImage: 'macOS-11'
  steps:
  - script: |
      brew update
      brew install pkg-config
      brew install libressl
      swift build --package-path Examples/Leaderboard/
- job: 'Carthage'
  pool:
    vmImage: 'macOS-11'
  steps:
  - script: carthage bootstrap --use-xcframeworks --platform macos
    workingDirectory: 'Examples/Leaderboard'

- job: 'CocoaPods'
  pool:
    vmImage: 'macOS-11'
  steps:
  - task: CocoaPods@0
    inputs:
      projectDirectory: 'Examples/Leaderboard'
  - task: Xcode@5
    inputs:
      actions: 'build'
      scheme: 'Leaderboard'
      sdk: 'macosx'
      configuration: 'Release'
      xcWorkspacePath: 'Examples/Leaderboard/Leaderboard.xcworkspace'
      xcodeVersion: specifyPath
      xcodeDeveloperDir: '/Applications/Xcode_13.0.app/Contents/Developer'


